### ISSUE TITLE
aflsmart run problem

### ISSUE THREAD

**Issue by cryptomadco** [aflsmart/aflsmart#22] opened 2020-03-10 00:34 UTC
Hi !
After following your tutorial I've successfully compiled aflsmart but when I run it with :

`timeout 24h $AFLSMART/afl-fuzz -m none -h -d -i $AFLSMART/testcases/aflsmart/wav -o out -w peach -g $AFLSMART/input_models/wav.xml -x $AFLSMART/dictionaries/wav.dict -e wav -- ./cli/wavpack -y @@ -o out`

I get the following error :

```
[-] PROGRAM ABORT : peach cannot be found. Please compile Peach and setup PATH environment variable correctly.
         Location : main(), afl-fuzz.c:8988
```

I don't know where the exact problem is .

Would you please help?

Thanks

**Comment by thuanpv** [comment] 2020-03-10 00:43
Hi,

Have you run this script after compiling AFLSmart: https://github.com/aflsmart/aflsmart/blob/master/setup_env.sh

Peach binaries are stored in $AFLSMART/peach-3.0.202-source/output/linux_x86_64_debug/bin.

Please let me know if the issue is gone.

Best regards,

Thuan

**Comment by cryptomadco** [comment] 2020-03-10 01:16
Thanks! the problem was that!

Non-related to this thread, do AFL++ uses aflsmart algorithm? seems aflsmart algorithm is pretty powerful among other afl forks!

Thanks

**Comment by thuanpv** [comment] 2020-03-10 04:03
AFL++ hasn't implemented AFLSmart's algorithm yet. However, the team recently added a custom mutator interface that can be used to implement AFLSmart. Please see this tweet for more information: https://twitter.com/andreafioraldi/status/1236618198696562688

**Comment by thuanpv** [comment] 2020-03-10 04:07
Since the issue has been resolved, I close it.

**Closed as completed by thuanpv** 2020-03-10 04:07 UTC
